var tpl = [
	'<div id="{uuid}" class="datepicker ui-d-n">',
	'	<div class="datepicker__mask"></div>',
	'	<div class="datepicker__main">',
	'		<div class="datepicker__header">',
	'			<div class="datepicker__time-toggle"></div>',
	'			<div class="datepicker__time-selector-list">',
	'				<div class="datepicker__time-selector-item">',
	'					<a href="javascript:;" class="datepicker__time-selector-arrow datepicker__time-selector-prev" id="_j_year_prev">&lt;</a>',
	'					<a href="javascript:;" class="datepicker__time-selector-text" id="_j_year_text">{year}年</a>',
	'					<a href="javascript:;" class="datepicker__time-selector-arrow datepicker__time-selector-next" id="_j_year_next">&gt;</a>',
	'				</div>',
	'				<div class="datepicker__time-selector-item">',
	'					<a href="javascript:;" class="datepicker__time-selector-arrow datepicker__time-selector-prev" id="_j_month_prev">&lt;</a>',
	'					<a href="javascript:;" class="datepicker__time-selector-text" id="_j_month_text">{month}月</a>',
	'					<a href="javascript:;" class="datepicker__time-selector-arrow datepicker__time-selector-next" id="_j_month_next" >&gt;</a>',
	'				</div>',
	'			</div>',
	'		</div>',
	'		<div class="datepicker__panel">',
	'			<ul class="datepicker__week-list">',
	'				<li class="datepicker__week-item">日</li>',
	'				<li class="datepicker__week-item">一</li>',
	'				<li class="datepicker__week-item">二</li>',
	'				<li class="datepicker__week-item">三</li>',
	'				<li class="datepicker__week-item">四</li>',
	'				<li class="datepicker__week-item">五</li>',
	'				<li class="datepicker__week-item">六</li>',
	'			</ul>',
	'			<div class="datepicker__day-wrap">',
	'				<ul class="datepicker__day-list datepicker__day-list-curr">',
	'					{all_days}',
	'				</ul>',
	'			</div>',
	'		</div>',
	'		',
	'		<div class="datepicker__footer">',
	'			<div class="datepicker__btn" id="_j_confirm_btn">确定</div>',
	'			<div class="datepicker__btn" id="_j_cancel_btn">取消</div>',
	'		</div>',
	'	</div>',
	'</div>'
].join("");

module.exports = tpl;
